### ISSUE TITLE
RTC implementation?

### ISSUE THREAD

**Issue by AmiManga** [UzixLS/mist1010-board#4]
Regarding RTC, 

I was able to setup the time and it works just fine! 
However while system is off, clock does not measure time, just remembers time when system was powered off. 
Is this proper behaviour or am I missing something? Should clock run all the time? 

Cheers,

R.

**Comment by UzixLS** [comment]
RTC should count time even when system powered off.
Check battery voltage - it must be between 2.0V and 3.5V for proper operation.

**Comment by AmiManga** [comment]
It appears that there was a firmware corruption in the ATtiny45. Fortunately, after re-flashing the firmware, everything is functioning correctly even after powering off. I recall that the clock initially performed well in offline mode. Glad to know it wasn't just my imagination!

Thank you

R.
