### ISSUE TITLE
Testing Tape IN

### ISSUE THREAD

**Issue by AmiManga** [UzixLS/mist1010-board#5]
Any suggestion how to test TAPE in? I am trying to find the core that can support this feature.
Anything specific I need to add to mist.ini? 

Cheers,

R.

**Comment by UzixLS** [comment]
You can check with ZX Spectrum core, no mist.ini editing required.

**Comment by AmiManga** [comment]
There are few Spectrum cores available for Mist. Any Spectrum core will do?

**Comment by UzixLS** [comment]
I know only one https://github.com/mist-devel/mist-binaries/tree/master/cores/spectrum

**Comment by AmiManga** [comment]
Thank you. I will give it a try.

R.
